### ISSUE TITLE
Error in firefox and google chrome

### ISSUE THREAD

**Issue by haylahi** [buke/odoo-web-pdf-preview-print#1]
hello,
It's a usefull and nice module!!!
When i try it, i have this error both in Firefox and  Chrome in wondows.
Firefox :
TypeError: this.get_action_manager(...) is undefined
http://172.20.10.3:8069/web/webclient/js:3222
Google :
Uncaught TypeError: Cannot call method 'get_title' of undefined
http://172.20.10.3:8069/web/webclient/js:3222

configuration_________
Openerp 7 lastest
Server : ubuntu 12.04

thks

**Comment by buke** [comment]
Test passed on  openerp-7.0-20130222-002152 .

Please update your openerp version to openerp-7.0-20130222-002152 or newer.

And I think it's a oe bug, cause i got the same error on openerp-7.0-20130112-002227 .

**Comment by haylahi** [comment]
Hi,
Well, i think u should modify your **openerp**.py description :
start server with :
./openerpserver --loal=web,web_pdf_preview
it's work like a charms for me.
Thk

**Comment by buke** [comment]
Well, when I got the error on  openerp-7.0-20130112-002227,  Press F5  to refresh the page , and it would be ok .

I doubt  it's the js loading problem.

The newer oe vision do NOT has the error and OE7 is NOT official release for now,  so we see if the newer oe vision has the error.

Thk
