### ISSUE TITLE
on firefox v23 version,can not preview the whole paper

### ISSUE THREAD

**Issue by andy3027** [buke/odoo-web-pdf-preview-print#2]
![preview](https://f.cloud.github.com/assets/2961775/1102624/6fbc2184-183b-11e3-85ad-1af94b14a9f6.jpg)

**Comment by buke** [comment]
I tested it on firefox 23.0.1 on windows 7 (64bit) and dot not find any problem.
![qq20130908134436](https://f.cloud.github.com/assets/1013738/1102680/f34987a4-1849-11e3-839b-8e1cc31f4e2b.jpg)

**Comment by buke** [comment]
Maybe you should upgrade your firefox ?
