### ISSUE TITLE
是不是不支持8.0？

### ISSUE THREAD

**Issue by nmglyy** [buke/odoo-web-pdf-preview-print#3]
我在8.0安装上好像没有什么效果。

**Comment by buke** [comment]
暂时不支持

**Comment by mynameisshiy** [comment]
步科，这个什么时候能支持上呢？

**Comment by buke** [comment]
亲，稍等哈，有空就弄上去。。。最近比较忙

Brain Wang 王步科
Skype: wangbuke | QQ: 17779104
WeChat: buke_wang
Mobile: +86 136 0000 4025 tel:%2B86%20136%200000%204025
Email: wangbuke@gmail.com mailto:wangbuke@gmail.com
