### ISSUE TITLE
service in odoo crash automatically

### ISSUE THREAD

**Issue by Anhlq87** [buke/odoo-web-pdf-preview-print#7]
Hi everybody,

I met a problem about service in odoo. Sometime service crash automatically. I don't know what's the problem. I checked in syslog file in Ubuntu. It have a message as: 
-> Jun 11 12:00:12 debian16 kernel: [2995203.489726] python[9366]: segfault at 3c ip 00007f0a47486d00 sp 00007f0a3ad66e20 error 4 in etree.so[7f0a473f7000+fa000]
I also checked memory but it's not problem. please everybody help me resolve this problem. Thanks a lot.

**Comment by buke** [comment]
it's not this module .  It seems like python lxml problem.
