### ISSUE TITLE
Odoo 9 version?

### ISSUE THREAD

**Issue by GillPotter** [buke/odoo-web-pdf-preview-print#9]
Hi, I found your module very useful in Odoo v8. I am trying to use it with v9 but without success. Do you have a plan to develop a v9 version?
Many thanks, Gill

**Comment by buke** [comment]
yes, but please wait for a while until I get time

**Comment by robpaz** [comment]
Hello Master Jedi,

Your module is great!!! but we really need it for Odoo v9!!!

We would love to give some donation if necessary!!

Thanks in advance!!

**Comment by buke** [comment]
release v9 , thank you
